<?php

return [
    1 => [
        'id' => 1,
        'name' => '1º Poomsae',
        'korean_name' => 'Taegeuk Il Jang',
        'video_id' => '6Vp6DywacIw',
        'has_detail_page' => true,
        'steps' => [
            "Are maki – Ap sogui | Defensa abajo – Paso corto",
            "Momtong bande jirugui – Ap sogui | Puñetazo al medio – Paso corto",
            "Are maki – Ap sogui | Defensa abajo – Paso corto",
            "Momtong bande jirugui – Ap sogui | Puñetazo al medio – Paso corto",
            "Are maki – Ap kubi sogui / Montong baro jirugui – Ap kubi sogui | Defensa abajo – Paso largo / Puñetazo al medio – Paso largo",
            "Momtong an maki – Ap sogui | Defensa al medio – Paso corto",
            "Momtong baro jirgui – Ap sogui | Puñetazo al medio – Paso corto",
            "Momtong an maki – Ap sogui | Defensa al medio – Paso corto",
            "Momtong baro jirgui – Ap sogui | Puñetazo al medio – Paso corto",
            "Are maki – Ap kubi sogui / Montong baro jirugui – Ap kubi sogui | Defensa abajo – Paso largo / Puñetazo al medio – Paso largo",
            "Olgul maki – Ap sogui | Defensa arriba – Paso corto",
            "Ap chagui / Momtong bande jirugui – Ap sogui | Patada fronta / Puñetazo al medio – Paso corto",
            "Olgul maki – Ap sogui | Defensa arriba – Paso corto",
            "Ap chagui / Momtong bande jirugui – Ap sogui | Patada fronta / Puñetazo al medio – Paso corto",
            "Are maki – Ap kubi sogui | Defensa abajo – Paso largo",
            "Momtong bande jirugui – Ap kubi sogui / KIHAP | Puñetazo al medio – Paso largo / GRITO"
        ]
    ],
    2 => [
        'id' => 2,
        'name' => '2º Poomsae',
        'korean_name' => 'Taegeuk I Jang',
        'video_id' => 'OHcfJj-wt9U',
        'has_detail_page' => true,
        'steps' => [
            "Are maki – Ap sogui | Defensa abajo – Paso corto",
            "Momtong bande jirugui – Ap kubi sogui | Puñetazo al medio – Paso largo",
            "Are maki – Ap sogui | Defensa abajo – Paso corto",
            "Momtong bande jirugui – Ap kubi sogui | Puñetazo al medio – Paso largo",
            "Momtong an maki – Ap sogui | Defensa al medio – Paso corto",
            "Momtong an maki – Ap sogui | Defensa al medio – Paso corto",
            "Are maki – Ap sogui | Defensa abajo – Paso corto",
            "Ap chagui / Olgul bande jirugui – Ap kubi sogui | Patada frontal / Puñetazo a la cara – Paso largo",
            "Are maki – Ap sogui | Defensa abajo – Paso corto",
            "Ap chagui / Olgul bande jirugui – Ap kubi sogui | Patada frontal / Puñetazo a la cara – Paso largo",
            "Olgul maki – Ap sogui | Defensa arriba – Paso corto",
            "Olgul maki – Ap sogui | Defensa arriba – Paso corto",
            "Momtong an maki – Ap sogui | Defensa al medio – Paso corto",
            "Momtong an maki – Ap sogui | Defensa al medio – Paso corto",
            "Are maki – Ap sogui | Defensa abajo – Paso corto",
            "Ap chagui / Momtong bande jirugui – Ap sogui | Patada frontal / Puñetazo al medio – Paso corto",
            "Ap chagui / Momtong bande jirugui – Ap sogui | Patada frontal / Puñetazo al medio – Paso corto",
            "Ap chagui / Momtong bande jirugui – Ap sogui / KIHAP | Patada frontal / Puñetazo al medio – Paso corto / GRITO"
        ]
    ],
    3 => [
        'id' => 3,
        'name' => '3º Poomsae',
        'korean_name' => 'Taegeuk Sam Jang',
        'video_id' => 's16_vF_k290',
        'has_detail_page' => true,
        'steps' => [
            "Are maki – Ap sogui | Defensa abajo – Paso corto",
            "Momtong dubon jirugui – Ap kubi sogui | Patada frontal / Doble puñetazo al medio – Paso largo",
            "Are maki – Ap sogui | Defensa abajo – Paso corto",
            "Momtong dubon jirugui – Ap kubi sogui | Patada frontal / Doble puñetazo al medio – Paso largo",
            "Sonnal an chigui – Ap sogui | Golpe con el canto de la mano al cuello, brazo cambiado – Paso corto",
            "Sonnal an chigui – Ap sogui | Golpe con el canto de la mano al cuello, brazo cambiado – Paso corto",
            "Jansonnal momtong bakat maki – Tuit kubi sogui / Momtong baro jirugui – Ap kubi sogui | Defensa al medio con un canto de la mano, de dentro hacia fuera – Paso largo con el peso hacia atrás / Puñetazo al medio, brazo cambiado – Paso largo",
            "Jansonnal momtong bakat maki – Tuit kubi sogui / Momtong baro jirugui – Ap kubi sogui | Defensa al medio con un canto de la mano, de dentro hacia fuera – Paso largo con el peso hacia atrás / Puñetazo al medio, brazo cambiado – Paso largo",
            "Momtong an maki – Ap sogui | Defensa al medio – Paso corto",
            "Momtong an maki – Ap sogui | Defensa al medio – Paso corto",
            "Are maki – Ap sogui | Defensa abajo – Paso corto",
            "Ap chagui / Momtong dubon jirugui – Ap kubi sogui | Patada fronta / Doble puñetazo al medio – Paso largo",
            "Are maki – Ap sogui | Defensa abajo – Paso corto",
            "Ap chagui / Momtong dubon jirugui – Ap kubi sogui | Patada fronta / Doble puñetazo al medio – Paso largo",
            "Are maki – Ap sogui / Momtong baro jirugui – Ap sogui | Defensa abajo – Paso corto / Puñetazo al medio – Paso corto",
            "Are maki – Ap sogui / Momtong baro jirugui – Ap sogui | Defensa abajo – Paso corto / Puñetazo al medio – Paso corto",
            "Ap chagui / Are maki – Ap sogui / Momtong baro jirugui – Ap sogui | Patada frontal / Defensa abajo – Paso corto / Puñetazo al medio – Paso corto",
            "Ap chagui / Are maki – Ap sogui / Momtong baro jirugui – Ap sogui / KIHAP | Patada frontal / Defensa abajo – Paso corto / Puñetazo al medio – Paso corto / GRITO"
        ]
    ],
    4 => [
        'id' => 4,
        'name' => '4º Poomsae',
        'korean_name' => 'Taegeuk Sa Jang',
        'video_id' => 'jRmC3P6eGk4',
        'has_detail_page' => true,
        'steps' => [
            "Sonnal momtong maki – Tuit kubi sogui | Defensa al medio con dos canos de mano – Paso largo con peso hacia atrás",
            "Pioson kut seuo jirugui – Ap kubi sogui | Golpe con la punta de los dedos al medio – Paso largo",
            "Sonnal momtong maki – Tuit kubi sogui | Defensa al medio con dos canos de mano – Paso largo con peso hacia atrás",
            "Pioson kut seuo jirugui – Ap kubi sogui | Golpe con la punta de los dedos al medio – Paso largo",
            "Chebi pum mok chigui – Ap kubi sogui | Defensa arriba y ataque al cuello con cantos de mano – Paso largo",
            "Ap chagui / Momtong baro jirugui – Ap kubi sogui | Patada frontal / Puñetazo al medio – Paso largo",
            "Yop chagui | Patada lateral",
            "Yop chagui / Sonnal momtong maki – Tuit kubi sogui | Patada lateral / Defensa al medio con dos canto de mano – Paso largo con peso hacia atrás",
            "Momtong bakat maki – Tuit kubi sogui | Defensa al medio hacia fuera – Paso largo con peso hacia atrás",
            "Ap chagui / Momtong an maki – Tuit kubi sogui | Patada frontal / Defensa al medio – Paso largo con el peso hacia atrás",
            "Momtong bakat maki – Tuit kubi sogui | Defensa al medio hacia fuera – Paso largo con peso hacia atrás",
            "Ap chagui / Momtong an maki – Tuit kubi sogui | Patada frontal / Defensa al medio – Paso largo con el peso hacia atrás",
            "Chebi pum mok chigui – Ap kubi sogui | Defensa arriba y ataque al cuello con cantos de mano – Paso largo",
            "Ap chagui / Dung chumok ape chigui – Ap kubi sogui | Patada frontal / Golpe frontal con los nudillos – Paso largo",
            "Momtong maki – Ap sogui | Defensa al medio – Paso corto",
            "Momtong baro jirugui – Ap sogui | Puñetazo al medio – Paso corto",
            "Momtong maki – Ap sogui | Defensa al medio – Paso corto",
            "Momtong baro jirugui – Ap sogui | Puñetazo al medio – Paso corto",
            "Momtong maki – Ap kubi sogui / Momtong dubon jirugui – Ap kubi sogui | Defensa al medio – Paso largo / Doble puñetazo al medio – Paso largo",
            "Momtong maki – Ap kubi sogui / Momtong dubon jirugui – Ap kubi sogui / KIHAP | Defensa al medio – Paso largo / Doble puñetazo al medio – Paso largo / GRITO"
        ]
    ],
    5 => [
        'id' => 5,
        'name' => '5º Poomsae',
        'korean_name' => 'Taegeuk Oh Jang',
        'video_id' => 'y-H5VQjcDwQ',
        'has_detail_page' => true,
        'steps' => [
            "Are maki – Ap kubi sogui | Defensa abajo – Paso largo",
            "Me chumok neryo yop chigui – Uen sogui | Golpe con la base del puño, de arriba hacia abajo, lateral – Paso a la izquierda",
            "Are maki – Ap kubi sogui | Defensa abajo – Paso largo",
            "Me chumok neryo yop chigui – Orun sogui | Golpe con la base del puño, de arriba hacia abajo, lateral – Paso a la derecha",
            "Momtong maki – Ap kubi sogui / Montong an maki – Ap kubi sogui | Defensa al medio – Paso largo/ Defensa al medio – Paso largo",
            "Ap chagui / Dung chumok ape chigui – Ap kubi sogui / Momtong an maki – Ap kubi sogui | Patada frontal / Golpe con los nudillos al frente – Paso largo / Defensa al medio – Paso largo",
            "Ap chagui / Dung chumok ape chigui – Ap kubi sogui / Momtong an maki – Ap kubi sogui | Patada frontal / Golpe con los nudillos al frente – Paso largo / Defensa al medio – Paso largo",
            "Dung chumok ape chigui – Ap kubi sogui | Golpe con los nudillos al frente – Paso largo",
            "Jansonnal momtong bakat maki – Tuit kubi sogui | Defensa con un canto de la mano, de dentro hacia fuera – Paso largo con peso hacia atrás",
            "Palkup dolyo chigui – Ap kubi sogui | Golpe circular con el codo – Paso largo",
            "Jansonnal momtong bakat maki – Tuit kubi sogui | Defensa con un canto de la mano, de dentro hacia fuera – Paso largo con peso hacia atrás",
            "Palkup dolyo chigui – Ap kubi sogui | Golpe circular con el codo – Paso largo",
            "Are maki – Ap kubi sogui / Momtong an maki – Ap kubi sogui | Defensa abajo – Paso largo / Defensa al medio – Paso largo",
            "Ap chagui / Are maki – Ap kubi sogui / Momtong an maki – Ap  kubi sogui | Patada frontal / Defensa abajo – Paso largo / Defensa al medio – Paso largo",
            "Olgul maki / Ap kubi sogui | Defensa arriba / Paso largo",
            "Yop chagui / Momtong palkup piochok chigui – Ap kubi sogui | Patada lateral / Golpe al medio con el codo, con agarre – Paso largo",
            "Olgul maki / Ap kubi sogui | Defensa arriba / Paso largo",
            "Yop chagui / Momtong palkup piochok chigui – Ap kubi sogui | Patada lateral / Golpe al medio con el codo, con agarre – Paso largo",
            "Are maki – Ap kubi sogui / Momtong an maki – Ap kubi sogui | Defensa abajo – Paso largo / Defensa al medio – Paso largo",
            "Ap chagui / Dung chumok ape chigui – Tuit koa sogui / KIHAP | Patada frontal / Golpe con los nudillos al frente – Posición con apoyo trasero / GRITO"
        ]
    ],
    6 => [
        'id' => 6,
        'name' => '6º Poomsae',
        'korean_name' => 'Taegeuk Yuk Jang',
        'video_id' => 'jieZpO_shxQ',
        'has_detail_page' => true,
        'steps' => [
            "Are maki – Ap kubi sogui | Defensa abajo – Paso largo",
            "Ap chagui / Momtong bakat maki – Tuit kubi sogui | Patada frontal / Defensa al medio hacia fuera – Paso largo con peso hacia atrás",
            "Are maki – Ap kubi sogui | Defensa abajo – Paso largo",
            "Ap chagui / Momtong bakat maki – Tuit kubi sogui | Patada frontal / Defensa al medio hacia fuera – Paso largo con peso hacia atrás",
            "Bituro jansonnal momtong bakat maki – Ap kubi sogui | Defensa arriba con un canto de la mano con brazo cambiado – Paso largo",
            "Dolyo chagui | Patada circular",
            "Olgul bakat maki – Ap kubi sogui | Defensa arriba hacia fuera – Paso largo",
            "Ap chagui / Momtong baro jirugui – Ap kubi sogui | Patada frontal / Puñetazo al medio – Paso largo",
            "Olgul bakat maki – Ap kubi sogui | Defensa arriba hacia fuera – Paso largo",
            "Ap chagui / Momtong baro jirugui – Ap kubi sogui | Patada frontal / Puñetazo al medio – Paso largo",
            "Gecho are maki – Naranji sogui | Doble defensa abajo – Posición neutra (pies paralelos)",
            "Bituro jansonnal momtong bakat maki – Ap kubi sogui | Defensa arriba con un canto de la mano con brazo cambiado – Paso largo",
            "Dolyo chagui / KIHAP | Patada circular / GRITO",
            "Are maki – Ap kubi sogui | Defensa abajo – Paso largo",
            "Ap chagui / Momtong bakat maki – Tuit kubi sogui | Patada frontal / Defensa al medio hacia fuera – Paso largo con peso hacia atrás",
            "Are maki – Ap kubi sogui | Defensa abajo – Paso largo",
            "Ap chagui / Momtong bakat maki – Tuit kubi sogui | Patada frontal / Defensa al medio hacia fuera – Paso largo con peso hacia atrás",
            "Sonnal momtong maki – Tuit kubi sogui | Defensa al medio con dos cantos de mano – Paso largo hacia atrás",
            "Sonnal momtong maki – Tuit kubi sogui | Defensa al medio con dos cantos de mano – Paso largo hacia atrás",
            "Batagson momtong maki – Ap kubi sogui | Defensa al medio con la palma de la mano – Paso largo",
            "Momtong baro jirugui – Ap kubi sogui | Puñetazo al medio – Paso largo",
            "Batagson momtong maki – Ap kubi sogui | Defensa al medio con la palma de la mano – Paso largo",
            "Momtong baro jirugui – Ap kubi sogui | Puñetazo al medio – Paso largo"
        ]
    ],
    7 => [
        'id' => 7,
        'name' => '7º Poomsae',
        'korean_name' => 'Taegeuk Chil Jang',
        'video_id' => 'OChGu0evclI',
        'has_detail_page' => true,
        'steps' => [
            "Batagson momtong an maki – Bom sogui | Defensa al medio con la palma de la mano, brazo cambiado – Bom sogui",
            "Ap chagui / Momtong maki – Bom sogui | Patada frontal / Defensa al medio – Bom sogui",
            "Batagson momtong an maki – Bom sogui | Defensa al medio con la palma de la mano, brazo cambiado – Bom sogui",
            "Ap chagui / Momtong maki – Bom sogui | Patada frontal / Defensa al medio – Bom sogui",
            "Sonnal are maki – Tuit kubi sogui | Defensa abajo con los dos cantos de mano – Paso largo con el peso hacia atrás",
            "Sonnal are maki – Tuit kubi sogui | Defensa abajo con los dos cantos de mano – Paso largo con el peso hacia atrás",
            "Goduro batagson momtong an maki – Bom sogui | Defensa al medio con la palma de la mano, brazo cambiado y con apoyo – Bom sogui",
            "Goduro dung chumok ape chigui | Golpe al frente con los nudillos, con apoyo – Bom sogui",
            "Goduro batagson momtong an maki – Bom sogui | Defensa al medio con la palma de la mano, brazo cambiado y con apoyo – Bom sogui",
            "Goduro dung chumok ape chigui | Defensa al medio con la palma de la mano, brazo cambiado y con apoyo – Bom sogui",
            "Bo chumok chumbi – Moa sogui | Movimiento especial de chumbi – Posición de firmes",
            "Dubon gawi maki – Ap kubi sogui | Doble defensa en tijera – Paso largo",
            "Dubon gawi maki – Ap kubi sogui | Doble defensa en tijera – Paso largo",
            "Gechio momtong maki – Ap kubi sogui | Doble defensa al medio – Paso largo",
            "Murup chigui / Du checho jirugui – Tuit koa sogui | Golpe con la rodilla ascendente / Doble puñetazo al frente (costillas) – Paso largo con el peso hacia atrás",
            "Ogkoro are maki – Ap kubi sogui | Defensa cruzada abajo – Paso largo",
            "Gechio momtong maki – Ap kubi sogui | Doble defensa al medio – Paso largo",
            "Murup chigui / Du checho jirugui – Tuit koa sogui | Golpe con la rodilla ascendente / Doble puñetazo al frente (costillas) – Paso largo con el peso hacia atrás",
            "Ogkoro are maki – Ap kubi sogui | Defensa cruzada abajo – Paso largo",
            "Dung chumok bakat chigui – Ap sogui | Golpe hacia fuera con los nudillos – Paso corto",
            "Piochok chagui / Momtong palkup piochok chigui – Chuchum sogui | Patada con agarre / Golpe al medio con el codo con agarre – Posición de montar a caballo",
            "Dung chumok bakat chigui – Ap sogui | Golpe hacia fuera con los nudillos – Paso corto",
            "Piochok chagui / Momtong palkup piochok chigui – Chuchum sogui | Patada con agarre / Golpe al medio con el codo con agarre – Posición de montar a caballo",
            "Jansonnal momtong yop maki – Chuchum sogui | Defensa lateral con un canto de la mano – Posición de montar a caballo",
            "Yop jirugui – Chuchum sogui / KIHAP | Puñetazo lateral – Posición de montar a caballo / GRITO"
        ]
    ],
    8 => [
        'id' => 8,
        'name' => '8º Poomsae',
        'korean_name' => 'Taegeuk Pal Jang',
        'video_id' => 'CkifSGXPhBY',
        'has_detail_page' => true,
        'steps' => [
            "Goduro momtong maki – Tuit kubi sogui / Momtong baro jirugui – Ap kubi sogui | Defensa al medio con apoyo – Paso largo con peso atrás / Puñetazo al medio – Paso largo",
            "Tuyo ap chagui / KIHAP / Momtong maki – Ap kubi sogui / Momtong dubong jirugui – Ap kubi sogui | Patada frontal con salto / GRITO / Defensa al medio – Paso largo / Doble puñetazo al medio – Paso largo",
            "Momtong bande jirugui – Ap kubi sogui | Puñetazo al medio – Paso largo",
            "Oe santul maki – Ap kubi sogui | Doble defensa abajo y arriba – Paso largo",
            "Dankio tok jirugui – Ap kubi sogui | Puñetazo a la mandibulaon agarre – Paso largo",
            "Oe santul maki – Ap kubi sogui | Doble defensa abajo y arriba – Paso largo",
            "Dankio tok jirugui – Ap kubi sogui | Puñetazo a la mandibulaon agarre – Paso largo",
            "Sonnal momtong  maki – Tuit kubi sogui | Defensa al medio con dos cantos de mano – Paso largo con peso atrás",
            "Momtong baro jirgui – Ap kubi sogui | Puñetazo al medio – Paso largo",
            "Ap chagui / Batangson momton maki – Bom sogui | Patada frontal / Defensa con la palma de la mano al medio – Bom sogui",
            "Sonnal momtong maki – Bom sogui | Defensa al medio con dos cantos de mano – Bom sogui",
            "Ap chagui / Momtong baro jirugui – Ap kubi sogui | Patada frontal / Puñetazo al medio – Paso largo",
            "Batangson momton maki – Bom sogui | Defensa con la palma de la mano al medio – Bom sogui",
            "Sonnal momtong maki – Bom sogui | Defensa al medio con dos cantos de mano – Bom sogui",
            "Ap chagui / Momtong baro jirugui – Ap kubi sogui | Patada frontal / Puñetazo al medio – Paso largo",
            "Batangson momton maki – Bom sogui | Defensa con la palma de la mano al medio – Bom sogui",
            "Goduro are maki – Tuit kubi sogui | Defensa abajo con apoyo – Paso largo con peso atrás",
            "Ap chagui / Tuyo ap chagui / KIHAP / Momtong maki – Ap kubi sogui / Momtong dubong jirugi – Ap kubi sogui | Patada frontal / Patada frontal con salto / GRITO / Defensa la medio – Paso largo / Doble puñetazo al medio – Paso largo",
            "Jansonnal momtong bakat maki – Tuit kubi sogui | Defensa con un canto de la mano de dentro hacia fuera – Paso largo con peso atrás",
            "Palkup dolyo chigui – Ap kubi sogui | Golpe circular con el codo – Paso largo",
            "Dung chumok ape chigui – Ap kubi sogui / Momtong baro jirugui – Ap kubi sogui | Golpe frontal con lo nudillo – Paso largo / Puñetazo al medio – Paso largo",
            "Jansonnal momtong bakat maki – Tuit kubi sogui | Defensa con un canto de la mano de dentro hacia fuera – Paso largo con peso atrás",
            "Palkup dolyo chigui – Ap kubi sogui | Golpe circular con el codo – Paso largo",
            "Dung chumok ape chigui – Ap kubi sogui / Momtong baro jirugui – Ap kubi sogui | Golpe frontal con lo nudillo – Paso largo / Puñetazo al medio – Paso largo"
        ]
    ],
    9 => [
        'id' => 9,
        'name' => 'Koryo',
        'korean_name' => 'Koryo',
        'video_id' => 'fmx-rUFCDQ4',
        'has_detail_page' => false,
        'steps' => []
    ],
    10 => [
        'id' => 10,
        'name' => 'Kumgang',
        'korean_name' => 'Kumgang',
        'video_id' => 'iPiqh72R2ms',
        'has_detail_page' => false,
        'steps' => []
    ],
];
